name = "hello-axum-cf"
main = "build/worker/shim.mjs"
compatibility_date = "2025-05-10"

[build]
command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && . $HOME/.cargo/env && cargo install -q worker-build && worker-build --release"